name: Sign WebExtension

on:
  push:
    branches: [ master ]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Sign WebExtension
      run: node_modules/.bin/web-ext sign
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
        WEB_EXT_ID: ${{ secrets.WEB_EXT_ID }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: web-ext-artifacts
        path: web-ext-artifacts
